#!/usr/bin/env sh

deploydir=/var/lib/tomcat7/webapps/ROOT

echo '[+] compile'
libdir=/usr/share/tomcat7/lib
export CLASSPATH=$libdir/servlet-api.jar:$libdir/jsp-api.jar:$libdir/catalina.jar:$libdir/tomcat-coyote.jar
javac TTTServlet.java *.java JSON-java/*.java

echo '[+] deploy'
mkdir -p $deploydir/WEB-INF
mkdir -p $deploydir/WEB-INF/classes
mkdir -p $deploydir/WEB-INF/classes/ee4216
cp WEB-INF/* $deploydir/WEB-INF/
mv *.class $deploydir/WEB-INF/classes/ee4216/
